### ISSUE TITLE
unwanted link created even if the image is already wrapped by a link

### ISSUE THREAD

**Issue by tlylt** [crookedneighbor/markdown-it-linkify-images#45]
At the moment, the following common markdown syntax will turn
```md
[![Minion](https://octodex.github.com/images/minion.png)](http://google.com)
```
into
```html
<p>
<a href="http://google.com">
<a href="https://octodex.github.com/images/minion.png" target="_self">
<img src="https://octodex.github.com/images/minion.png">
</a>
</a>
</p>
```

The duplicated <a> tag is not compliant with HTML specs.

Expected outcome: Skip performing linkfy if image is already wrapped by link_open and link_close.

Hi @crookedneighbor please let me know what you think? I am happy to create a PR to implement it if this change is helpful.

**Comment by crookedneighbor** [comment]
Sounds good to me. Go for it!

**Comment by crookedneighbor** [comment]
This is out in v3.0.0!

**Comment by tlylt** [comment]
> This is out in v3.0.0!

Hey @crookedneighbor thanks for the quick action! Tested and works 🔥
