### ISSUE TITLE
How to build ./dist version for browsers?

### ISSUE THREAD

**Issue by dereks** [crookedneighbor/markdown-it-linkify-images#9]
Comparing this to other markdown-it plugins, it looks like there should be a Makefile that calls browserify to create the files in ./dist/.

How are the files in ./dist/ created?  Thanks!

**Comment by crookedneighbor** [comment]
Sorry, didn't see this until now. The files are created by running `npm run build`.

If you'd like to PR to include a Makefile to make this fall more in line with the other markdown-it plugins, feel free.
